version: '3.7'
services:
  web:
    build: ./
    ports:
      - 3000:3000
    environment:
      DOCKER_HOST: db
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
    depends_on:
      - db
    tty: true
  db:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
volumes:
  bundle:
  data: